Adding project quota to the datatable
pulibrary/tigerdata-app pull request #1077
Opened 2024-11-27 22:51 UTC by JaymeeH

adding storage capacity and usage to the dashboard presenter
passing the session id through the welcome controller
refs #1030

2024-11-27 22:51 UTC, JaymeeH commented
![Screenshot 2024-11-27 at 1 47 28 PM](https://github.com/user-attachments/assets/5a3c9c22-5108-4387-8ef1-c1ced3482bcd)

2024-12-03 21:46 UTC, JaymeeH commented
![Screenshot 2024-12-03 at 4 45 31 PM](https://github.com/user-attachments/assets/28f6b69d-8fcd-4d32-8328-3dcdb39a011c)

2024-12-04 18:47 UTC, JaymeeH commented
![Screenshot 2024-12-04 at 1 47 16 PM](https://github.com/user-attachments/assets/1de3aed0-ab9f-43ed-82a6-9b97ed2bbcf7)

2024-12-05 15:37 UTC, carolyncole requested changes
@JaymeeH nice work.  It looks like the percentage is not getting calculated.  Was this intended? I also wonder if the fact that the size is a hash instead of a string will cause some issues. 

At the very least can you clean up the method you made unused?

2024-12-05 15:37 UTC, carolyncole commented on app/models/project.rb
> -    requested_capacity = storage_capacity_xml
Can you also clean up the storage_capacity_xml function? https://github.com/pulibrary/tigerdata-app/blob/26bf465c12a856282cbd10065a0ade1b3a11d70d/app/models/project.rb#L237

2024-12-05 15:37 UTC, carolyncole commented on app/presenters/project_dashboard_presenter.rb
> +    # figure out how to calculate percentage of storage used with different and unpredictable units
I think storage is now a hash.  I wonder if there needs to be some updates to this code.  https://github.com/pulibrary/tigerdata-app/blob/main/app/models/project_metadata.rb#L149

2024-12-05 16:44 UTC, carolyncole approved these changes
Thanks @JaymeeH!  Nice step towards the finished product.

2024-12-05 16:44 UTC, merged