Ensures that the directory path is disabled for editing projects (unless the user is a system administrator)
pulibrary/tigerdata-app pull request #1090
Opened 2024-12-05 20:47 UTC by jrgriffiniii

Resolves #1046

2024-12-10 15:19 UTC, carolyncole submitted a review, later dismissed
@jrgriffiniii It looks like you are not testing your code change anywhere, maybe you forgot to commit some changes?

2024-12-10 15:19 UTC, carolyncole commented on spec/system/project_spec.rb
> +  let(:superuser) { FactoryBot.create(:superuser, uid: "root") }
@jrgriffiniii should this line be removed since it is unused?

2024-12-16 16:04 UTC, kelynch commented
It looks like this branch needs to be updated with the latest changes from main.  When I ran the test suite, `/spec/system/project_roles_spec.rb:209` produced an error.

2024-12-16 16:55 UTC, kelynch requested changes
It looks like this branch needs to be updated with the latest changes from main. When I ran the test suite, /spec/system/project_roles_spec.rb:209 produced an error.

2024-12-16 20:15 UTC, carolyncole approved these changes
Thanks @jrgriffiniii.  Looks great!

2024-12-16 20:30 UTC, merged