Prototyping an initial implementation for the disk storage quota usage component in the Project Show View
pulibrary/tigerdata-app pull request #1146
Opened 2024-12-18 15:06 UTC by jrgriffiniii

Advances #1099

2024-12-20 17:21 UTC, carolyncole commented
@jrgriffiniii Do these new components work, or are they just display elements?  If they are just display elements we might no want to merge this PR.  We have been trying to keep elements that do not work off the display.

2025-01-21 13:36 UTC, carolyncole commented
There must be a conlict in how these are being calculated...

Note 44.8 vs 43.7

dashboard:
![Screenshot 2025-01-21 at 8 34 02 AM](https://github.com/user-attachments/assets/3eb19f2c-14f5-4d01-a950-b611ec4ac608)

details:
![Screenshot 2025-01-21 at 8 34 19 AM](https://github.com/user-attachments/assets/27be24f5-f955-42c7-a23d-28464848ce7b)

2025-01-21 13:37 UTC, carolyncole submitted a review, later dismissed
I think the numbers on the dashboard and details need to match.  Otherwise this is ok...

2025-01-21 15:09 UTC, jrgriffiniii commented
It was determined that we should be using kilobytes for user-friendliness (during the check-in meeting on 01/21/25)

2025-01-21 15:13 UTC, carolyncole commented on app/presenters/project_show_presenter.rb
> +    1.0/(1024.0**1)
I think this needs to be 1000 vs 1024

2025-01-21 15:14 UTC, jrgriffiniii commented on app/presenters/project_show_presenter.rb
> +    1.0/(1024.0**1)
Thank you, I am changing this now.

2025-01-21 15:14 UTC, carolyncole commented on app/presenters/project_show_presenter.rb
> +    1.0/(1024.0**3)
Ditto, here 1000 vs 1024

2025-01-24 14:23 UTC, carolyncole commented
@jrgriffiniii I deployed this to staging and saw the dashboard is no longer showing the total unit:
![Screenshot 2025-01-24 at 8 58 27 AM](https://github.com/user-attachments/assets/33c75392-8929-4acb-898e-745be8ed5fdf)

2025-01-24 14:24 UTC, carolyncole requested changes
@jrgriffiniii another small bug.  Sorry.  Not sure why I did not see it the last time...

2025-01-24 14:24 UTC, carolyncole commented on app/models/project.rb
> +    "0 {default_storage_unit}"
I believe this needs to change
```suggestion
    "0 #{default_storage_unit}"
```

2025-01-24 19:18 UTC, carolyncole approved these changes
Thanks @jrgriffiniii

2025-01-24 19:18 UTC, merged