First pass at validating an XML document against the TigerData XSD
pulibrary/tigerdata-app pull request #899
Opened 2024-08-29 16:52 UTC by hectorcorrea

Works toward #896

2024-08-30 12:02 UTC, hectorcorrea commented on lib/tasks/xml_schema.rake
> +  end
`use_local_xml_xsd(xsd)` is a horrible hack but that's the only way I could get Nokogiri to validate the XML against the XSD successfully.

2024-10-09 12:30 UTC, carolyncole reviewed
This is great work @hectorcorrea!  Just one question.

2024-10-09 12:30 UTC, carolyncole commented on lib/assets/xml.xsd
@hectorcorrea what is this file?  Is it needed?

2024-10-09 12:42 UTC, carolyncole requested changes
Ok, so maybe we can add a comment,  just to link the two files up...

2024-10-09 12:42 UTC, carolyncole commented on lib/assets/xml.xsd
> +<?xml version='1.0'?>
```suggestion
<!-- Allows us to utilize Nokogiri for the validation.  For some reason utilizing the copy at  https://www.w3.org/2001/xml.xsd causes issues.  See xml_schema rake task for more information -->
<?xml version='1.0'?>
```

2024-10-09 12:45 UTC, carolyncole approved these changes
Thanks @hectorcorrea!  My partially caffeinated brain is playing the part of us a year from now...  When we think what is this file and delete it...

2024-10-09 12:47 UTC, hectorcorrea commented
@carolyncole agree, this is something we'll forget as soon as *squirrel* :)

2024-10-09 12:48 UTC, merged